[23/Mar/2017 20:15:22] INFO [httpproxy.views:160] GET http://localhost:8080/blazegraph/namespace?describe-each-named-graph=false
[23/Mar/2017 20:15:22] DEBUG [httpproxy.views:170] Response body: 
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:nodeID="node1bbu6fn0ox52">
	<rdf:type rdf:resource="http://rdfs.org/ns/void#Dataset"/>
	<title xmlns="http://purl.org/dc/terms/">kb</title>
	<Namespace xmlns="http://www.bigdata.com/rdf#/features/KB/">kb</Namespace>
	<sparqlEndpoint xmlns="http://rdfs.org/ns/void#" rdf:resource="http://localhost:8080/blazegraph/namespace/kb/sparql"/>
	<uriRegexPattern xmlns="http://rdfs.org/ns/void#">^.*</uriRegexPattern>
</rdf:Description>

</rdf:RDF>
[23/Mar/2017 20:15:22] INFO [httpproxy.views:160] POST http://localhost:8080/blazegraph/namespace/kb/sparql
[23/Mar/2017 20:15:22] ERROR [django.request:231] Internal Server Error: /namespace/kb/sparql
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/httpproxy/views.py", line 82, in dispatch
    response = super(HttpProxy, self).dispatch(request, *args, **kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/httpproxy/views.py", line 147, in post
    return self.get_response(body=request.body, headers=headers)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/httpproxy/views.py", line 166, in get_response
    response = urllib.request.urlopen(request)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 501: Not Implemented
[23/Mar/2017 20:15:22] INFO [httpproxy.views:160] GET http://localhost:8080/blazegraph/namespace?describe-each-named-graph=false
[23/Mar/2017 20:15:22] DEBUG [httpproxy.views:170] Response body: 
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:nodeID="node1bbu6fn0ox53">
	<rdf:type rdf:resource="http://rdfs.org/ns/void#Dataset"/>
	<title xmlns="http://purl.org/dc/terms/">kb</title>
	<Namespace xmlns="http://www.bigdata.com/rdf#/features/KB/">kb</Namespace>
	<sparqlEndpoint xmlns="http://rdfs.org/ns/void#" rdf:resource="http://localhost:8080/blazegraph/namespace/kb/sparql"/>
	<uriRegexPattern xmlns="http://rdfs.org/ns/void#">^.*</uriRegexPattern>
</rdf:Description>

</rdf:RDF>
[23/Mar/2017 20:15:22] WARNING [django.request:143] Not Found: /status
[23/Mar/2017 20:15:22] INFO [httpproxy.views:160] GET http://localhost:8080/blazegraph/namespace?describe-each-named-graph=false
[23/Mar/2017 20:15:22] DEBUG [httpproxy.views:170] Response body: 
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:nodeID="node1bbu6fn0ox54">
	<rdf:type rdf:resource="http://rdfs.org/ns/void#Dataset"/>
	<title xmlns="http://purl.org/dc/terms/">kb</title>
	<Namespace xmlns="http://www.bigdata.com/rdf#/features/KB/">kb</Namespace>
	<sparqlEndpoint xmlns="http://rdfs.org/ns/void#" rdf:resource="http://localhost:8080/blazegraph/namespace/kb/sparql"/>
	<uriRegexPattern xmlns="http://rdfs.org/ns/void#">^.*</uriRegexPattern>
</rdf:Description>

</rdf:RDF>
[23/Mar/2017 20:15:22] INFO [httpproxy.views:160] POST http://localhost:8080/blazegraph/namespace/kb/sparql
[23/Mar/2017 20:15:22] ERROR [django.request:231] Internal Server Error: /namespace/kb/sparql
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/httpproxy/views.py", line 82, in dispatch
    response = super(HttpProxy, self).dispatch(request, *args, **kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/httpproxy/views.py", line 147, in post
    return self.get_response(body=request.body, headers=headers)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/httpproxy/views.py", line 166, in get_response
    response = urllib.request.urlopen(request)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/NANOMINE/anaconda2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 501: Not Implemented
[23/Mar/2017 20:22:50] WARNING [django.request:143] Not Found: /favicon.ico
